version: '3.9'
services:
  api:
      container_name: api
      build:
        context: ./apps/api
        dockerfile: Dockerfile.dev
      ports:
        - "8080:8080"
      volumes:
        - ./apps/api:/app
      environment:
        - ENV=development
      depends_on:
        - db
  db:
    image: postgres:alpine3.20
    container_name: postgres-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    volumes:
      - go-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
volumes:
  go-data: