version: '3.9'
services:
  db:
    image: postgres:alpine3.20
    container_name: postgres-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    volumes:
      - go-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
volumes:
  go-data: