# Base image
FROM golang:1.24-bullseye

# Enable CGO and install libwebp for go-webp
ENV CGO_ENABLED=1

# Install necessary packages
RUN apt-get update && apt-get install -y \
  libwebp-dev \
  curl

# Install Air (hot reload tool)
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

# Set working directory
WORKDIR /app

# Copy go.mod and download dependencies early
COPY go.mod go.sum ./
RUN go mod download

# Copy rest of source code
COPY . .

# Default command for air
CMD ["air"]
